# Generated by Django 5.0.6 on 2024-06-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('certificate_number', models.CharField(max_length=50)),
                ('commercial_name', models.CharField(max_length=50)),
                ('ilk', models.CharField(max_length=20)),
                ('net_power_engine', models.IntegerField()),
                ('torque', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('fuel_consumption', models.FloatField()),
                ('energy_level', models.CharField(max_length=1)),
                ('pollution_level', models.CharField(max_length=10)),
                ('noise_level', models.FloatField()),
                ('guarantee_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmergencySpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OptionalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
