# Generated by Django 5.0.6 on 2024-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_car_accepted_date_car_car_type_car_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='emergency_spec',
        ),
        migrations.RemoveField(
            model_name='car',
            name='optional_facilities',
        ),
        migrations.AddField(
            model_name='car',
            name='emergency_spec',
            field=models.ManyToManyField(to='account.emergencyspec'),
        ),
        migrations.AddField(
            model_name='car',
            name='optional_facilities',
            field=models.ManyToManyField(to='account.optionalspec'),
        ),
    ]
